export const TOGGLE_OPEN_CONTACT = "TOGGLE_OPEN_CONTACT";
export const TOGGLE_OPEN_ABOUT = "TOGGLE_OPEN_ABOUT";
export const SET_EMAIL_NAME = "SET_EMAIL_NAME"
export const SET_EMAIL_ADDRESS = "SET_EMAIL_ADDRESS"
export const SET_EMAIL_SUBJECT = "SET_EMAIL_SUBJECT"
export const SET_EMAIL_MESSAGE = "SET_EMAIL_MESSAGE"
